name: Continuous deployment - Assignment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: mvn -B clean install --file pom.xml

  deploy:
    runs-on: ubuntu-latest
    depends-on: [ build ]
    steps:
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ronanclancy/side
        tags: ${{github.run_number}}