name: Continuous deployment - Assignment

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/home/assignmant
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test with Maven
        run: mvn test

  build:
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - run: mvn -B clean test --file pom.xml

  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Get time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYY-MM-DD-HH-mm-ss'

      - name: Create tag
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          export TAG=ronanclancy/assingmant-${{ steps.time.outputs.time }}
          echo "::set-env name=TAG::$TAG"

      - name: Build Container image
        run: docker build -t $TAG .

      - name: Publish Docker image
        run: docker push ronanclancy/side